### ISSUE TITLE
코드 분리작업 이후 생긴 에러에 관해

### ISSUE THREAD

**Issue by andrew0416** [Seoultech-SE-22/Seoultech-SE-22Team#134]
1. 처음 싱글 플레이 모드에서 봇들을 선택하고 start 버튼을 누를때, 게임 화면으로 가지는 대신 메인메뉴로 돌아옵니다.
두번째로 싱글 플레이 모드에서 봇들을 선택하고 start 버튼을 누르는 경우에는 정상적으로 게임 화면으로 넘어가집니다.

2. 스토리모드도 1과 마찬가지의 에러가 발생하며 추가로 argument 갯수 에러가 납니다.
그래서 스토리모드에 진입이 되지 않습니다.

3. 색약모드가 색상을 선택하는 것과 현재 색상을 표시해주는 부분을 제외하고는 적용되지 않습니다.

**Comment by rivkode** [comment]
@wedongguk 최신 버전에서 os 경로 바꿔볼래 ?

@kang9366 

아래 사진처럼 2번은 import 문제 같은데 내일 같이 수정해볼까 ?
![image](https://user-images.githubusercontent.com/109144975/235618248-305f798e-1c8e-4d66-96aa-4a88dfffd55d.png)

3번도 이전 버전에서는 잘 동작했으니 import 나 함수를 서로 호출하는 과정에서 좀 꼬인 것 같은데 이 부분도 같이 할 수 있을 듯 ?

**Comment by rivkode** [comment]
그리고 창수가 위에 있는 문제들 때문에 코드 분리작업 이전 코드로 작업을 했어서 지금 PR을 못날리고 있어
이 부분도 같이 오늘 줌으로 얘기해보자
문제 해결이 늦어지면 다시 코드 분리작업 전으로 돌린 후에 PR 받고 다시 작업 하고
빠르게 해결 가능한 상황이면 해결하고 창수하고 같이 얘기하면서 변경된 부분에 대해서 말해보면 될 것 같에
